repos:
  - repo: https://github.com/GitGuardian/ggshield
    rev: v1.45.0   # The ggshield version for your environment
    hooks:
      - id: ggshield
        name: ggshield (with .env support)
        entry: python -c "import os; from dotenv import load_dotenv, find_dotenv; load_dotenv(find_dotenv()); os.execvp('ggshield', ['ggshield'] + os.sys.argv[1:])"
        language: system
        pass_filenames: true
        types: [text]
