name: GitGuardian Secret Scan

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ggshield-scan:
    name: GitGuardian Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run GitGuardian Shield CLI
        run: |
          docker run --rm \
            -e GITGUARDIAN_API_KEY="${{ secrets.GG_API_KEY }}" \
            -v "$(pwd):/repo" \
            gitguardian/ggshield:v1.45.0 ggshield secret scan path /repo --recursive --verbose

      - name: Upload scan report (always)
        uses: actions/upload-artifact@v4
        if: always()
        
        with:
          name: ggshield-report
          path: ggshield-report.json
          if-no-files-found: ignore





