name: GitGuardian Secret Scan

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"   

jobs:
  ggshield-scan:
    name: GitGuardian Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run GitGuardian Shield
        uses: gitguardian/ggshield-action@v1.45.0
        with:
          args: "scan repo ."
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GG_API_KEY }}

      - name: Upload scan report (always)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ggshield-report
          path: ggshield-report.json
          if-no-files-found: ignore


