name: Secret Scan

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Daily scan at midnight UTC

jobs:
  ggshield-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ggshield
        run: pip install ggshield

      - name: Run ggshield scan
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GG_API_KEY }}
        run: ggshield secret scan repo .
