name: Secret Scan

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Daily scan at midnight UTC

jobs:
  ggshield-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: GitGuardian Shield Action
        uses: gitguardian/ggshield-action@v1
        with:
          args: "scan repo . --api-key ${{ secrets.GG_API_KEY }}"
